"""add_news_articles_table

Revision ID: 941c73ffbd8c
Revises: 670a0da83f87
Create Date: 2025-05-21 22:30:00.000000 # Placeholder, will be actual timestamp

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941c73ffbd8c'
down_revision: Union[str, None] = '670a0da83f87' # Assuming previous was klines table creation
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_article_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('snippet', sa.String(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('article_url', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sentiment_score_external', sa.Float(), nullable=True),
    sa.Column('sentiment_category_derived', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_article_id')
    )
    op.create_index(op.f('ix_news_articles_external_article_id'), 'news_articles', ['external_article_id'], unique=False) # unique=False for index, constraint handles uniqueness
    op.create_index(op.f('ix_news_articles_id'), 'news_articles', ['id'], unique=False)
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_articles_symbol'), 'news_articles', ['symbol'], unique=False)
    op.create_index('ix_news_articles_symbol_published_at', 'news_articles', ['symbol', 'published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_news_articles_symbol_published_at', table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_symbol'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_id'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_external_article_id'), table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###
